### ISSUE TITLE
Funcionamiento deficiente en móviles

### ISSUE THREAD

**Issue by ManuelLR** [AgoraUS-G1-1617/Deliberations#1]

**Comment by juanrarodriguez18** [comment]
No es una funcionalidad de vital importancia, desde el inicio del proyecto se está probando las nuevas funcionalidades y mejoras que se están desarrollando en distintas resoluciones (incluidas las móviles) para que se vea lo mejor posible, pero se considera que no es necesario una remodelación completa de la aplicación para adaptarse a dichas resoluciones.
