### ISSUE TITLE
Comunicación entre usuarios

### ISSUE THREAD

**Issue by josearodriguez** [AgoraUS-G1-1617/Deliberations#13]
Se podría añadir una nueva funcionalidad donde un nuevo usuario autenticado pueda enviarle un mensaje a otro usuario. 

El objetivo es: un usuario le envía a otro un mensaje y le llega una notificación de mensajes nuevos no leídos. No se va a permitir responder a un mensaje ni la creación de carpetas.

**Comment by juanrarodriguez18** [comment]
Revisado y funcionando.
