### ISSUE TITLE
Ordenación de hilos

### ISSUE THREAD

**Issue by juanrarodriguez18** [AgoraUS-G1-1617/Deliberations#19]
Ordenar los hilos según la fecha del último mensaje publicado del Hilo.

**Comment by ManuelLR** [comment]
En espera del #14

**Comment by ManuelLR** [comment]
Se ha decidido que la propiedad de fecha del último comentario no será transient y persistirá en la base de datos para que ordenar los hilos por fecha sea más eficiente.
