### ISSUE TITLE
Eclipse como Sudo

### ISSUE THREAD

**Issue by juanrarodriguez18** [AgoraUS-G1-1617/Deliberations#27]

**Comment by juanrarodriguez18** [comment]
Ejecutar Eclipse como Sudo desde el lanzador de aplicaciones del escritorio.

**Comment by ManuelLR** [comment]
Este issue no va aquí. 
Su sitio es el repositorio de configuración: https://github.com/EGCG2/ConfigurationVMS

Cuando lo cambies cierra este issue
