### ISSUE TITLE
Homogeneizar estilo con resto de módulos

### ISSUE THREAD

**Issue by jjxp** [AgoraUS-G1-1617/Deliberations#3]
Se debe mejorar y homogeneizar, en la medida de lo posible, el estilo de la aplicación de tal forma que se asemeje lo máximo posible a la de los restantes módulos para mejorar la experiencia de usuario.

**Comment by juanrarodriguez18** [comment]
Finalmente se ha llegado a la decisión de que al no haber un acuerdo de estilos general de todas las aplicaciones que componen el sistema de AgoraUS, dicha homogeneización no es posible, por lo que se intentará llevar un estilo lo más limpio posible.
