### ISSUE TITLE
[UML] Añadir propiedad en Thread (lastComment)

### ISSUE THREAD

**Issue by ManuelLR** [AgoraUS-G1-1617/Deliberations#35]
Falta la propiedad derivada en Thread denominada lastComment que será un date. Servirá para ordenar los hilos por ordenes de comentarios.

**Comment by juanrarodriguez18** [comment]
Añadida la propiedad al proyecto y actualizado el UML.

**Comment by ManuelLR** [comment]
debe modificarse puesto que no podía usarse como heredada

**Comment by ManuelLR** [comment]
Concretamente la propiedad a añadir tras solucionar el issue #19 es lastUpdate de tipo Date perteneciente a la clase Thread
