### ISSUE TITLE
Añadir página de perfil de usuario

### ISSUE THREAD

**Issue by barmardom** [AgoraUS-G1-1617/Deliberations#37]
Cada usuario puede ver su propio perfil con alguno de sus datos.

**Comment by juanrarodriguez18** [comment]
Ahí además hay un tema interesante, porque en Auth te piden una serie de datos como la provincia el sexo y demás al registrarte y nosotros los tenemos en nuestra base de datos en la tabla "User" (Obviamente en blanco y sin rellenar) y sería interesante preguntarle a los de Auth si con su API se pueden obtener esos datos y en caso contrario podría ser una posible mejora que nos favoreciera a ambos.

**Comment by barmardom** [comment]
Exacto, eso mismo he comentado con @josearodriguez esta misma tarde, seria una buena idea.

**Comment by juanrarodriguez18** [comment]
Si existe lo que yo me refería creo issue

**Comment by juanrarodriguez18** [comment]
Revisada y funciona correctamente.
