### ISSUE TITLE
¿Query incorrecta? (problema heredado)

### ISSUE THREAD

**Issue by ManuelLR** [AgoraUS-G1-1617/Deliberations#39]
Esta [consulta](https://github.com/AgoraUS-G1-1617/Deliberations/blob/develop/src/main/java/repositories/CommentRepository.java#L19) apunta a una propiedad inexistente.

Revisar para comprobar su correcto funcionamiento.

**Comment by juanrarodriguez18** [comment]
Propiedad inexistente? 
![image](https://cloud.githubusercontent.com/assets/8267403/20497921/590aa4f2-b02b-11e6-91d7-1828b0957a73.png)

**Comment by ManuelLR** [comment]
Tienes toda la razón, la query está bien formulada. La miré mal.
Cierro el issue
