### ISSUE TITLE
Login fallido despues de intentar acceder a url no permitida

### ISSUE THREAD

**Issue by josearodriguez** [AgoraUS-G1-1617/Deliberations#42]
Si intentamos acceder a un url(sin estar logeado) que solo esta disponible para usuario autenticados nuestra aplicación nos redirige a la ventana para hacer login. Hasta el momento todo es correcto. Pero si intentamos acceder con usuario existente, no nos dejara.

Para ver el error hacer los siguientes pasos:

1. Entrar en la pagina principal: [http://beta.deliberaciones.agoraus1.egc.duckdns.org](http://beta.deliberaciones.agoraus1.egc.duckdns.org)

2. Acceder a una pagina no permitida para usuario no autenticados:  [http://beta.deliberaciones.agoraus1.egc.duckdns.org/message/user/received.do?page=1](http://beta.deliberaciones.agoraus1.egc.duckdns.org/message/user/received.do?page=1)

3. Por ultimo, intentar hacer login.

**Comment by ManuelLR** [comment]
@josearodriguez Causa del problema:
Este problema es heredado y ocurre porque ellos para el Login usan su propio método ubicado en user en lugar del genérico (al que te reenvía el mensaje de error). 
Posibles soluciones:
- Mudar el Login que tienen en user al método genérico (security). Es lo habitual y como debía ser. 
- Eliminar todo el controlador de login en el security y enlazar las urls al de "user"

**Comment by juanrarodriguez18** [comment]
Si no os importa me asigno esta Issue, ya que tengo experiencia en éste tipo de cosas, realicé una modificación similar en el Hackathon.
