### ISSUE TITLE
Corregir datos mostrados en el perfil de usuario

### ISSUE THREAD

**Issue by barmardom** [AgoraUS-G1-1617/Deliberations#46]
- [x] Se debe eliminar de la vista del perfil del usuario el "surname" debido a que no es una propiedad que se nos pida en el registro
- [x] Mostrar comunidad y edad (después de #45)
- [x] Cambiar el estilo de como se muestra el profile del usuario integrando en la misma vista sus estadísticas

**Comment by juanrarodriguez18** [comment]
Revisado y funcionando.
