### ISSUE TITLE
Redirección en cambio de idioma

### ISSUE THREAD

**Issue by Dionakra** [AgoraUS-G1-1617/Deliberations#51]
Buenas.

Utilizando la versión beta del código (https://beta.deliberaciones.agoraus1.egc.duckdns.org/) al navegar por la página y querer cambiar el idioma de una página en concreto, ésta redirige a la página principal. Por ejemplo, si estamos en el apartado de login (https://beta.deliberaciones.agoraus1.egc.duckdns.org/user/login.do) y nos interesa cambiar el idioma, al pulsar sobre el icono correspondiente nos redirige a la página principal.

En este punto tampoco es un problema grave, pero en el momento en el que se encuentre un usuario en un nivel 5 de profundidad por acción en interfaz puede ser bastante molesto.

En resumen, hacer que el cambio de idioma te deje en la página en la que estés.

**Comment by juanrarodriguez18** [comment]
Revisado y funcionando.
