### ISSUE TITLE
Limitación descripción y título hilos

### ISSUE THREAD

**Issue by ManuelLR** [AgoraUS-G1-1617/Deliberations#57]
No se permiten crear hilos con una descripción o títulos muy largos pero tampoco notifica como un error que sean demasiado largos

**Comment by juanrarodriguez18** [comment]
No estoy del todo de acuerdo con esta Issue, existe una limitación tecnológica, me expico, no es como en Twitter que hay una limitación establecida de 140 caracteres, es que habrás sobrepasado lo que cabe en un STRING de MySQL, y por tanto es normal que no te avise porque no se considera un comportamiento "normal" de un usuario, esto cabría la posibilidad de discutirlo para la descripción y los comentarios de los hilos, pero para los títulos no, porque se entiende que un título es algo sencillo y corto y nunca va a sobrepasar la limitación de caracteres de un STRING.

**Comment by ManuelLR** [comment]
Hay dos maneras de solucionar este error:
- Ver cual es el límite de longitud de un string en mysql y poner la anotación @Column(length=1000).
- Poner la anotación que permite textos largos en mysql. (@Lob)

**Comment by jjxp** [comment]
Ver 143f478ff570fd043247546afad83b02aecbd4f8 y 0080bf409f86386f5a95aa4bf9ea57a5b999499d
