### ISSUE TITLE
Enviar mensajes a uno mismo

### ISSUE THREAD

**Issue by ManuelLR** [AgoraUS-G1-1617/Deliberations#64]
No está permitido enviarte un mensaje a ti mismo.

¿Por que?

**Comment by josearodriguez** [comment]
No es coherente. Cuando una persona se envía un mensaje a si misma es porque no quiere olvidar algo(como recordatorio). Para esa funcionalidad ya existen muchas alternativas en Internet.

**Comment by juanrarodriguez18** [comment]
Yo también pienso lo mismo que @josearodriguez veo mejor cerrar esta Issue.
