### ISSUE TITLE
Permitir ver el perfil de otros usuarios

### ISSUE THREAD

**Issue by ManuelLR** [AgoraUS-G1-1617/Deliberations#65]
La propuesta iría enfocada a no poder listar todos los usuarios si no a que cada vez que se muestre un nombre de usuario o su foto sea un enlace para poder ver su información.

Habría que cambiar las siguientes cosas para que sea aceptable:
- [x] Cuando se muestre el dashboard de otro usuario no debería mostrar ninguna información acerca de los mensajes.
- [x] Tampoco debería mostrar la dirección de correo electrónico puesto que tenemos la opción  interna del sistema a enviarse mensajes entre ellos.

Posibles mejoras basadas en esta:
- [ ] Añadir en el dashboard un botón/enlace para enviarle mensajes (que lleve a la vista de enviar mensajes con su nombre de usuario prerrellenado)
- [ ] Añadir tema de amigos o seguidores.

**Comment by juanrarodriguez18** [comment]
Revisado y funcionando.
