### ISSUE TITLE
Mejorar visualización de karma en el dashboard

### ISSUE THREAD

**Issue by ManuelLR** [AgoraUS-G1-1617/Deliberations#67]
Actualmente se muestra de dos maneras, con un numero y con medallas y su descripción.

Además de aparecer por duplicado la misma información, usan escalas distintas puesto que el karma numérico empieza en 0 y la descripción de las medallas en 1

**Comment by juanrarodriguez18** [comment]
¿Cómo? Creo que te has desorientado, el Karma y el sistema de recompensas no tienen absolutamente nada que ver, de hecho son cosas completamente distintas, tu puedes haber creado muchos hilos y haber participado mucho en la comunidad pero no tener un Karma positivo por las aportaciones que has hecho, es un error de concepto, así que cierro la Issue.
