### ISSUE TITLE
Cambiar fotos portada

### ISSUE THREAD

**Issue by ManuelLR** [AgoraUS-G1-1617/Deliberations#70]
- Incluir la nuestra como equipo de desarrollo
- Incluir la de las jornadas de EGC como equipo de AgoraUS

Debe hacerse tras el #69

**Comment by jjxp** [comment]
Debe cambiarse el formato y presentar la información de otra forma, sin incluir la fotografía del equipo de trabajo por considerarse irrelevante. (Ver #69)
