### ISSUE TITLE
Quitar todos los print del codigo

### ISSUE THREAD

**Issue by josearodriguez** [AgoraUS-G1-1617/Deliberations#79]
Se ha detectado en el código fuente muchas lineas  System.out.println(), esto debería de ser quitado.

**Comment by ManuelLR** [comment]
Se deben quedar en los test puesto que al ejecutar travis no sabríamos que test habría fallado solo que ha fallado.

**Comment by juanrarodriguez18** [comment]
Revisado y correcto.
