### ISSUE TITLE
Cambiar URL de autenticación

### ISSUE THREAD

**Issue by jjxp** [AgoraUS-G1-1617/Deliberations#87]
El módulo de autenticación con el que el subsistema se estaba comunicando ha dejado de estar desplegado en el dominio egcauth.tk

Se debe corregir la URL.

**Comment by jjxp** [comment]
Se trataba de un error de uptime del servidor donde está desplegado. Sin embargo, se deja abierta ya que sigue siendo necesario cambiar la URL por la del sistema desplegado en integración continua.

**Comment by ManuelLR** [comment]
Este issue permanece abierto a la espera de que autha tenga un certificado ssl válido para poder hacer las peticiones mediante https
