### ISSUE TITLE
Información de un usuario

### ISSUE THREAD

**Issue by josearodriguez** [AgoraUS-G1-1617/Deliberations#9]
Dado un usuario autentificado en el sistema se podría añadir una nueva funcionalidad para poder ver la información básica de este usuario en una nueva pagina.

- [x] mostrar nombre de usuario
- [x] visión global de su karma
- [x] total de mensajes creados
- [x] total de hilos creados
- [x] comentarios totales

**Comment by juanrarodriguez18** [comment]
Revisado, actúa correctamente.
